// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Debt struct {
	ID         int64
	SupplierID int64
	Balance    int64
	Paid       bool
	Date       pgtype.Timestamptz
}

type Payment struct {
	ID         int64
	Balance    int64
	SupplierID int64
	Date       pgtype.Timestamptz
}

type Sale struct {
	ID      int64
	Balance int64
	Date    pgtype.Timestamptz
}

type Supplier struct {
	ID           int64
	Name         string
	CreationDate pgtype.Timestamptz
}
