// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateDebt(ctx context.Context, arg CreateDebtParams) (Debt, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateSale(ctx context.Context, balance int64) (Sale, error)
	CreateSupplier(ctx context.Context, name string) (Supplier, error)
	DeleteDebt(ctx context.Context, id int64) error
	DeletePayment(ctx context.Context, id int64) error
	DeleteSale(ctx context.Context, id int64) error
	DeleteSupplier(ctx context.Context, id int64) error
	GetDebt(ctx context.Context, id int64) (Debt, error)
	GetPayment(ctx context.Context, id int64) (Payment, error)
	GetSale(ctx context.Context, id int64) (Sale, error)
	GetSupplier(ctx context.Context, id int64) (Supplier, error)
	LastTenSales(ctx context.Context) ([]Sale, error)
	ListDebts(ctx context.Context, arg ListDebtsParams) ([]Debt, error)
	ListPayments(ctx context.Context, arg ListPaymentsParams) ([]Payment, error)
	ListSales(ctx context.Context, arg ListSalesParams) ([]Sale, error)
	ListSupplier(ctx context.Context, arg ListSupplierParams) ([]Supplier, error)
	UpdateDebt(ctx context.Context, arg UpdateDebtParams) (Debt, error)
	UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (Payment, error)
	UpdateSale(ctx context.Context, arg UpdateSaleParams) (Sale, error)
	UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error)
}

var _ Querier = (*Queries)(nil)
